In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:5]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [19]:
slice_of_arr[:] = 99


In [20]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [21]:
arr


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy[:] = 100

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
arr_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr_2d.shape

(3, 3)

In [31]:
arr_2d[1][1]

5

In [33]:
bool_arr = arr>4

In [34]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [35]:
arr[bool_arr]

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [36]:
arr[arr>4]

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])