# Numpy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
myarr = np.array(mylist)

In [4]:
myarr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [15]:
len(np.linspace(0,5,21))

21

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5,6)

array([[0.54698722, 0.62340888, 0.96095301, 0.22192086, 0.49172297,
        0.73014777],
       [0.12041348, 0.85622235, 0.6581292 , 0.47081666, 0.92146729,
        0.1580935 ],
       [0.63604985, 0.04704393, 0.45104969, 0.548196  , 0.95936605,
        0.40832682],
       [0.20944648, 0.88122697, 0.27208113, 0.58458752, 0.20593823,
        0.53249203],
       [0.62265538, 0.4194678 , 0.07589334, 0.24828996, 0.54376138,
        0.93723145]])

In [18]:
np.random.randn(10)

array([ 0.71637702, -0.06047461, -0.46458214,  0.59905269,  1.41492758,
        0.09387663,  0.62387122,  0.83432884, -0.50378121, -0.13886432])

In [20]:
np.random.randn(2,3)

array([[ 1.45442646, -0.45942904,  0.1619333 ],
       [ 1.05501316,  0.00764472, -1.50400635]])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
np.random.randint(0,101,10)

array([ 8, 18, 92,  6, 11, 87, 78, 14, 37, 22])

In [27]:
np.random.seed(10)

In [28]:
np.random.rand(4)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388])

In [41]:
arr = np.arange(0,24)

In [42]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
ranarr = np.random.randint(0,101,10)

In [49]:
ranarr


array([ 89,  93,  29,   8,  73,   0,  40,  36,  16, 100])

In [45]:
ranarr.max()

100

In [47]:
ranarr.min()

0

In [50]:
ranarr.argmax()

9

In [48]:
ranarr.argmin()

5

In [52]:
ranarr.dtype

dtype('int64')