In [1]:
import numpy as np

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [7]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr/arr

/var/folders/fc/jnw05f292vj0sbz5b5pw6nvc0000gn/T/ipykernel_98706/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.sum()

45

In [13]:
arr.max()

9

In [14]:
arr.var()

8.25

In [15]:
arr.std()

2.8722813232690143

In [16]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr_2d = np.arange(0,25).reshape(5,5)

In [22]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr_2d.sum()

300

In [20]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [21]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])